name: 💡 功能请求
title: '[Feat]: '
description: 通过这个议题提供建议和想法
labels: ['功能 (Enhancement)']

body:
  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 清晰的描述此功能的理由。
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 解决方案
      description: 详细的描述你想要实现或改进的功能。
    validations:
      required: true
