name: Release

on:
  push:
    tags:
      # Match tags in the format of "major.minor.patch", e.g., "1.2.3"
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  TAURI_RAW_NAME: "hoyo_gacha"
  TAURI_PRODUCT_NAME: "HoYo.Gacha"

jobs:
  release:
    name: Build, Sign and Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rust environment
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Setup Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node and setup cache
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install app dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      # Release build, not 'cicd'
      - name: Build app (release)
        run: pnpm build

      - name: Prepare executable and PDB files
        shell: bash
        run: |
          cp \
            "${{ github.workspace }}/target/release/${{ env.TAURI_RAW_NAME }}.exe" \
            "${{ github.workspace }}/${{ env.TAURI_PRODUCT_NAME }}-${{ github.ref_name }}-unsigned.exe"
          cp \
            "${{ github.workspace }}/target/release/${{ env.TAURI_RAW_NAME }}.pdb" \
            "${{ github.workspace }}/${{ env.TAURI_PRODUCT_NAME }}-${{ github.ref_name }}.pdb"
          echo "Executable and PDB files prepared in workspace root"
          find "${{ github.workspace }}" -maxdepth 1 -type f -name "${{ env.TAURI_PRODUCT_NAME }}*.*"

      - name: Upload unsigned executable
        uses: actions/upload-artifact@v7
        id: upload-unsigned-exe
        with:
          path: ${{ github.workspace }}/${{ env.TAURI_PRODUCT_NAME }}-${{ github.ref_name }}-unsigned.exe
          archive: false
          retention-days: 7

      - name: Upload PDB file
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/${{ env.TAURI_PRODUCT_NAME }}-${{ github.ref_name }}.pdb
          archive: false
          retention-days: 7

      - name: Submit signing request to SignPath
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
          project-slug: ${{ secrets.SIGNPATH_PROJECT_SLUG }}
          signing-policy-slug: ${{  secrets.SIGNPATH_SIGNING_POLICY_SLUG }}
          artifact-configuration-slug: ${{ secrets.SIGNPATH_ARTIFACT_CONFIGURATION_SLUG }}
          github-artifact-id: ${{ steps.upload-unsigned-exe.outputs.artifact-id }}
          output-artifact-directory: ${{ github.workspace }}/signed
          wait-for-completion: true
          wait-for-completion-timeout-in-seconds: 3600 # Wait up to 1 hour for signing to complete

      - name: Copy signed executable to Workspace root
        shell: bash
        run: |
          echo "Looking for signed artifact in: ${{ github.workspace }}/signed"
          mv \
            "${{ github.workspace }}/signed/${{ env.TAURI_PRODUCT_NAME }}-${{ github.ref_name }}-unsigned.exe" \
            "${{ github.workspace }}/signed/${{ env.TAURI_PRODUCT_NAME }}-${{ github.ref_name }}.exe"
          cp \
            "${{ github.workspace }}/signed/${{ env.TAURI_PRODUCT_NAME }}-${{ github.ref_name }}.exe" \
            "${{ github.workspace }}/${{ env.TAURI_PRODUCT_NAME }}.exe"
          echo "Signed executable copied to workspace root"
          find "${{ github.workspace }}" -maxdepth 1 -type f -name "${{ env.TAURI_PRODUCT_NAME }}.*"

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/signed/${{ env.TAURI_PRODUCT_NAME }}-${{ github.ref_name }}.exe
          archive: false
          retention-days: 7

      - name: Create Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ github.workspace }}/${{ env.TAURI_PRODUCT_NAME }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
